on: push
name: Build and publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # https://github.com/actions/docker does not currently have any release tags
      # at all! avoid using it since pinning to `master` is too risky because
      # inputs may be refactored when they migrate it to new style yaml format.
      - name: Docker Registry Login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # TODO(mroth): potentially refactor the distributed cache docker build
      # script shared across a few repos into a reusable GH action. Note to
      # self, this will be probably be easier once the various buildx/containerd
      # patches I've been poking at with the Docker team are landed in a stable
      # release.
      - name: Caching Build
        env:
          PUSH_CACHE: "1"
        run: sh -c "BRANCH=${GITHUB_REF##*/} ID=gh ci/build.sh"
      # Only tagged releases starting with "v" will be auto-published (weak
      # attempt at encouraging semver adherence), trigger on the tag push event.
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        run: docker run -e LIVE -e NPM_TOKEN openlaw/client:packager ./scripts/release.sh
        env:
          LIVE: "1"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
