on: push
name: Linters on push

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/checkout@v1
    - runs: npm ci
    - runs: npm run lint
    - runs: npm run style

  lint-shell:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - name: Shellcheck Lint
      uses: actions/bin/shellcheck@master
      with:
        args: scripts/*.sh ci/*.sh
