on: release
name: Publish to NPM on release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # all of the below are duplicative of build.yml, and documented there.
      # TODO(mroth): do we really need this here anymore? or in new setup can
      # we move this into a gated part of build perhaps? 
    - uses: actions/checkout@v1
    - name: Docker Registry Login
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Caching Build
      env:
        PUSH_CACHE: "1"
      run: sh -c "BRANCH=${GITHUB_REF##*/} ID=gh ci/build.sh"

    # actual release stuffs
    - name: Debug Event
      run: cat $GITHUB_EVENT_PATH
    # ^^^ left over from when we were debugging release happening 3x, leave for
    # now to see what is happening in new world.
    # TODO: delete debug event later when no longer needed.

    - name: Publish
      run: docker run -it openlaw/client:packager ./scripts/release.sh
      env:
        LIVE: "1"
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
